import Head from "next/head";
import BarcodeScanner from "@/components/BarcodeScanner";
import dynamic from "next/dynamic";
const BgImage = dynamic(() => import("@/components/BGImage"), {
  ssr: false,
});

export default function BarcodeScannerPage() {
  return (
    <>
      <Head>
        <title>scanner-test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BarcodeScanner />
    </>
  );
}
